enableHardenedMode: false

enableScripts: false

nodeLinker: node-modules

packageExtensions:
  "eslint-plugin-jsx-a11y@*":
    peerDependencies:
      eslint: "^3 || ^4 || ^5 || ^6 || ^7 || ^8 || ^9 || ^10"
