blank_issues_enabled: false
contact_links:
  - name: Traefik Community Support
    url: https://community.traefik.io/
    about: If you have a question, or are looking for advice, please post on our Discuss forum! The community loves to chime in to help. Happy Coding!
