declare module '@styled-system/css';
declare module '@styled-system/variant';
declare module '@styled-system/theme-get';
declare module 'lodash.merge';
declare module 'lodash.omit';
declare module 'lodash.pick';
declare module '*.woff';
declare module '*.woff2';
declare module 'react-eva-icons';