import { createThemeContract } from '@vanilla-extract/css';

export const tokens = createThemeContract({
  colors: {
    primary: null,
    contentBg: null,
    hiContrast: null,
    loContrast: null,
    focusOutline: null,
    divider: null,
    background: null,
    foreground: null,
    muted: null,
    mutedForeground: null,
    card: null,
    cardForeground: null,
    popover: null,
    popoverForeground: null,
    border: null,
    input: null,
    accent: null,
    accentForeground: null,
    destructive: null,
    destructiveForeground: null,
    ring: null,
  },
  fonts: { rubik: null },
  space: { 1: null, 2: null, 3: null, 4: null, 5: null, 6: null, 7: null, 8: null, 9: null },
  sizes: {
    1: null,
    2: null,
    3: null,
    4: null,
    5: null,
    6: null,
    7: null,
    8: null,
    9: null,
    10: null,
  },
  fontSizes: {
    0: null,
    1: null,
    2: null,
    3: null,
    4: null,
    5: null,
    6: null,
    7: null,
    8: null,
    9: null,
    10: null,
    11: null,
    12: null,
  },
  fontWeights: { light: null, regular: null, medium: null, semiBold: null, bold: null },
  radii: { 1: null, 2: null, 3: null, 4: null, round: null, pill: null },
  zIndices: { 1: null, 2: null, 3: null, 4: null, max: null },
});
