import { recipe } from '@vanilla-extract/recipes';

import { tokens } from './tokens.css';

export const padding = recipe({
  base: {},
  variants: {
    p: {
      1: { padding: tokens.space[1] },
      2: { padding: tokens.space[2] },
      3: { padding: tokens.space[3] },
      4: { padding: tokens.space[4] },
      5: { padding: tokens.space[5] },
      6: { padding: tokens.space[6] },
      7: { padding: tokens.space[7] },
      8: { padding: tokens.space[8] },
      9: { padding: tokens.space[9] },
    },
    pt: {
      1: { paddingTop: tokens.space[1] },
      2: { paddingTop: tokens.space[2] },
      3: { paddingTop: tokens.space[3] },
      4: { paddingTop: tokens.space[4] },
      5: { paddingTop: tokens.space[5] },
      6: { paddingTop: tokens.space[6] },
      7: { paddingTop: tokens.space[7] },
      8: { paddingTop: tokens.space[8] },
      9: { paddingTop: tokens.space[9] },
    },
    pr: {
      1: { paddingRight: tokens.space[1] },
      2: { paddingRight: tokens.space[2] },
      3: { paddingRight: tokens.space[3] },
      4: { paddingRight: tokens.space[4] },
      5: { paddingRight: tokens.space[5] },
      6: { paddingRight: tokens.space[6] },
      7: { paddingRight: tokens.space[7] },
      8: { paddingRight: tokens.space[8] },
      9: { paddingRight: tokens.space[9] },
    },
    pb: {
      1: { paddingBottom: tokens.space[1] },
      2: { paddingBottom: tokens.space[2] },
      3: { paddingBottom: tokens.space[3] },
      4: { paddingBottom: tokens.space[4] },
      5: { paddingBottom: tokens.space[5] },
      6: { paddingBottom: tokens.space[6] },
      7: { paddingBottom: tokens.space[7] },
      8: { paddingBottom: tokens.space[8] },
      9: { paddingBottom: tokens.space[9] },
    },
    pl: {
      1: { paddingLeft: tokens.space[1] },
      2: { paddingLeft: tokens.space[2] },
      3: { paddingLeft: tokens.space[3] },
      4: { paddingLeft: tokens.space[4] },
      5: { paddingLeft: tokens.space[5] },
      6: { paddingLeft: tokens.space[6] },
      7: { paddingLeft: tokens.space[7] },
      8: { paddingLeft: tokens.space[8] },
      9: { paddingLeft: tokens.space[9] },
    },
    px: {
      1: { paddingLeft: tokens.space[1], paddingRight: tokens.space[1] },
      2: { paddingLeft: tokens.space[2], paddingRight: tokens.space[2] },
      3: { paddingLeft: tokens.space[3], paddingRight: tokens.space[3] },
      4: { paddingLeft: tokens.space[4], paddingRight: tokens.space[4] },
      5: { paddingLeft: tokens.space[5], paddingRight: tokens.space[5] },
      6: { paddingLeft: tokens.space[6], paddingRight: tokens.space[6] },
      7: { paddingLeft: tokens.space[7], paddingRight: tokens.space[7] },
      8: { paddingLeft: tokens.space[8], paddingRight: tokens.space[8] },
      9: { paddingLeft: tokens.space[9], paddingRight: tokens.space[9] },
    },
    py: {
      1: { paddingTop: tokens.space[1], paddingBottom: tokens.space[1] },
      2: { paddingTop: tokens.space[2], paddingBottom: tokens.space[2] },
      3: { paddingTop: tokens.space[3], paddingBottom: tokens.space[3] },
      4: { paddingTop: tokens.space[4], paddingBottom: tokens.space[4] },
      5: { paddingTop: tokens.space[5], paddingBottom: tokens.space[5] },
      6: { paddingTop: tokens.space[6], paddingBottom: tokens.space[6] },
      7: { paddingTop: tokens.space[7], paddingBottom: tokens.space[7] },
      8: { paddingTop: tokens.space[8], paddingBottom: tokens.space[8] },
      9: { paddingTop: tokens.space[9], paddingBottom: tokens.space[9] },
    },
  },
});

export const margin = recipe({
  base: {},
  variants: {
    m: {
      1: { margin: tokens.space[1] },
      2: { margin: tokens.space[2] },
      3: { margin: tokens.space[3] },
      4: { margin: tokens.space[4] },
      5: { margin: tokens.space[5] },
      6: { margin: tokens.space[6] },
      7: { margin: tokens.space[7] },
      8: { margin: tokens.space[8] },
      9: { margin: tokens.space[9] },
    },
    mt: {
      1: { marginTop: tokens.space[1] },
      2: { marginTop: tokens.space[2] },
      3: { marginTop: tokens.space[3] },
      4: { marginTop: tokens.space[4] },
      5: { marginTop: tokens.space[5] },
      6: { marginTop: tokens.space[6] },
      7: { marginTop: tokens.space[7] },
      8: { marginTop: tokens.space[8] },
      9: { marginTop: tokens.space[9] },
    },
    mr: {
      1: { marginRight: tokens.space[1] },
      2: { marginRight: tokens.space[2] },
      3: { marginRight: tokens.space[3] },
      4: { marginRight: tokens.space[4] },
      5: { marginRight: tokens.space[5] },
      6: { marginRight: tokens.space[6] },
      7: { marginRight: tokens.space[7] },
      8: { marginRight: tokens.space[8] },
      9: { marginRight: tokens.space[9] },
    },
    mb: {
      1: { marginBottom: tokens.space[1] },
      2: { marginBottom: tokens.space[2] },
      3: { marginBottom: tokens.space[3] },
      4: { marginBottom: tokens.space[4] },
      5: { marginBottom: tokens.space[5] },
      6: { marginBottom: tokens.space[6] },
      7: { marginBottom: tokens.space[7] },
      8: { marginBottom: tokens.space[8] },
      9: { marginBottom: tokens.space[9] },
    },
    ml: {
      1: { marginLeft: tokens.space[1] },
      2: { marginLeft: tokens.space[2] },
      3: { marginLeft: tokens.space[3] },
      4: { marginLeft: tokens.space[4] },
      5: { marginLeft: tokens.space[5] },
      6: { marginLeft: tokens.space[6] },
      7: { marginLeft: tokens.space[7] },
      8: { marginLeft: tokens.space[8] },
      9: { marginLeft: tokens.space[9] },
    },
    mx: {
      1: { marginLeft: tokens.space[1], marginRight: tokens.space[1] },
      2: { marginLeft: tokens.space[2], marginRight: tokens.space[2] },
      3: { marginLeft: tokens.space[3], marginRight: tokens.space[3] },
      4: { marginLeft: tokens.space[4], marginRight: tokens.space[4] },
      5: { marginLeft: tokens.space[5], marginRight: tokens.space[5] },
      6: { marginLeft: tokens.space[6], marginRight: tokens.space[6] },
      7: { marginLeft: tokens.space[7], marginRight: tokens.space[7] },
      8: { marginLeft: tokens.space[8], marginRight: tokens.space[8] },
      9: { marginLeft: tokens.space[9], marginRight: tokens.space[9] },
    },
    my: {
      1: { marginTop: tokens.space[1], marginBottom: tokens.space[1] },
      2: { marginTop: tokens.space[2], marginBottom: tokens.space[2] },
      3: { marginTop: tokens.space[3], marginBottom: tokens.space[3] },
      4: { marginTop: tokens.space[4], marginBottom: tokens.space[4] },
      5: { marginTop: tokens.space[5], marginBottom: tokens.space[5] },
      6: { marginTop: tokens.space[6], marginBottom: tokens.space[6] },
      7: { marginTop: tokens.space[7], marginBottom: tokens.space[7] },
      8: { marginTop: tokens.space[8], marginBottom: tokens.space[8] },
      9: { marginTop: tokens.space[9], marginBottom: tokens.space[9] },
    },
  },
});

export const layout = recipe({
  base: {},
  variants: {
    // Flex direction
    direction: {
      row: { flexDirection: 'row' },
      column: { flexDirection: 'column' },
      rowReverse: { flexDirection: 'row-reverse' },
      columnReverse: { flexDirection: 'column-reverse' },
    },
    // TBC alignItems/alignContent?
    align: {
      start: { alignItems: 'flex-start' },
      center: { alignItems: 'center' },
      end: { alignItems: 'flex-end' },
      stretch: { alignItems: 'stretch' },
      baseline: { alignItems: 'baseline' },
    },
    justify: {
      start: { justifyContent: 'flex-start' },
      center: { justifyContent: 'center' },
      end: { justifyContent: 'flex-end' },
      spaceBetween: { justifyContent: 'space-between' },
      spaceAround: { justifyContent: 'space-around' },
      spaceEvenly: { justifyContent: 'space-evenly' },
    },
  },
});

export const typography = recipe({
  base: {},
  variants: {
    size: {
      0: { fontSize: tokens.fontSizes[0] },
      1: { fontSize: tokens.fontSizes[1] },
      2: { fontSize: tokens.fontSizes[2] },
      3: { fontSize: tokens.fontSizes[3] },
      4: { fontSize: tokens.fontSizes[4] },
      5: { fontSize: tokens.fontSizes[5] },
      6: { fontSize: tokens.fontSizes[6] },
      7: { fontSize: tokens.fontSizes[7] },
      8: { fontSize: tokens.fontSizes[8] },
      9: { fontSize: tokens.fontSizes[9] },
      10: { fontSize: tokens.fontSizes[10] },
      11: { fontSize: tokens.fontSizes[11] },
      12: { fontSize: tokens.fontSizes[12] },
    },
  },
});
