name: Production build test

on:
  pull_request:

env:
  SAFE_CHAIN_MINIMUM_PACKAGE_AGE_HOURS: 72  # 3 days

jobs:
  faency:
    name: Production build test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: enable corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Setup safe-chain
        run: |
          set -e
          curl -fsSL https://github.com/AikidoSec/safe-chain/releases/download/1.4.7/install-safe-chain.sh -o /tmp/install-safe-chain.sh
          echo "7934118ae7f81f69ac9e849c044b0c7009618b91859f06ec8b941258a43d98ed7d3712f9fde85304b7fcbbf723d2f0b5034e063342a675b38878e9cd2b587a04  /tmp/install-safe-chain.sh" | sha512sum -c -
          sh /tmp/install-safe-chain.sh --ci

      - name: Install production dependencies
        run: yarn workspaces focus --all --production

      - name: Patch
        run: yarn patch-package

      - name: Build
        run: yarn build
