name: Release

on:
  push:
    branches:
      - master

env:
  SAFE_CHAIN_MINIMUM_PACKAGE_AGE_HOURS: 360  # 15 days

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  faency:
    name: Release
    if: github.repository == 'traefik/faency'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: enable corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Setup safe-chain
        run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.sh | sh -s -- --ci

      - name: Install dependencies
        run: yarn workspaces focus --all

      - name: Patch
        run: yarn patch-package

      - name: Build
        run: yarn build

      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
